on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: |
          DOCKER_BUILDKIT=1 docker build . --tag ghcr.io/chneau/draw
          docker login ghcr.io --username $ --password "${{ github.token }}"
          docker push ghcr.io/chneau/draw
